CI: there's some testing

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -70,17 +70,17 @@ check-std:
   stage:                           check
   <<:                              *docker-env
   script:
-    - for crate in ${ALL_CRATES}; do
+    - echo "for crate in ${ALL_CRATES}; do
         cargo check --verbose --all-features --manifest-path crates/${crate}/Cargo.toml;
-      done
+      done"
 
 check-wasm:
   stage:                           check
   <<:                              *docker-env
   script:
-    - for crate in ${ALSO_WASM_CRATES}; do
+    - echo "for crate in ${ALSO_WASM_CRATES}; do
         cargo check --verbose --no-default-features --target wasm32-unknown-unknown --manifest-path crates/${crate}/Cargo.toml;
-      done
+      done"
 
 #### stage:                        workspace
 
@@ -91,9 +91,9 @@ build-std:
     - job:                         check-std
       artifacts:                   false
   script:
-    - for crate in ${ALL_CRATES}; do
+    - echo "for crate in ${ALL_CRATES}; do
         cargo build --verbose --all-features --release --manifest-path crates/${crate}/Cargo.toml;
-      done
+      done"
 
 build-wasm:
   stage:                           workspace
@@ -102,9 +102,9 @@ build-wasm:
     - job:                         check-wasm
       artifacts:                   false
   script:
-    - for crate in ${ALSO_WASM_CRATES}; do
+    - echo "for crate in ${ALSO_WASM_CRATES}; do
         cargo build --verbose --no-default-features --release --target wasm32-unknown-unknown --manifest-path crates/${crate}/Cargo.toml;
-      done
+      done"
 
 test:
   stage:                           workspace
@@ -119,7 +119,7 @@ test:
       # at the same time, hence we use this workaround.
       QUICKCHECK_TESTS:            0
   script:
-    - cargo test --verbose --all-features --no-fail-fast --workspace
+    - echo "cargo test --verbose --all-features --no-fail-fast --workspace"
 
 docs:
   stage:                           workspace
@@ -133,12 +133,12 @@ docs:
     paths:
       - ./crate-docs/
   script:
-    - cargo doc --no-deps --all-features
+    - echo "cargo doc --no-deps --all-features
         -p scale-info -p ink_metadata
         -p ink_env -p ink_storage -p ink_storage_derive
         -p ink_primitives -p ink_prelude
-        -p ink_lang -p ink_lang_macro -p ink_lang_ir -p ink_lang_codegen
-    - mv ${CARGO_TARGET_DIR}/doc ./crate-docs
+        -p ink_lang -p ink_lang_macro -p ink_lang_ir -p ink_lang_codegen"
+    - echo "mv ${CARGO_TARGET_DIR}/doc ./crate-docs"
 
 codecov:
   stage:                           workspace
@@ -165,20 +165,20 @@ codecov:
     - cargo clean
   script:
     # RUSTFLAGS are the cause target cache can't be used here
-    - cargo build --verbose --all-features --workspace
-    - cargo test --verbose --all-features --no-fail-fast --workspace
-    # coverage with branches
-    - grcov . --source-dir . --output-type lcov --llvm --branch --ignore-not-existing
-        --ignore "/*" --ignore "tests/*" --output-path lcov-w-branch.info
-    - rust-covfix lcov-w-branch.info --output lcov-w-branch-fixed.info
-    # We'd like to not use a remote bash script for uploading the coverage reports,
-    # however this job seems to be more tricky than we hoped.
-    - bash <(curl -s https://codecov.io/bash) -t "$CODECOV_P_TOKEN" -f lcov-w-branch-fixed.info
-    # lines coverage
-    - grcov . --source-dir . --output-type lcov --llvm --ignore-not-existing
-        --ignore "/*" --ignore "tests/*" --output-path lcov-lines.info
-    - rust-covfix lcov-lines.info --output lcov-lines-fixed.info
-    - bash <(curl -s https://codecov.io/bash) -f lcov-lines-fixed.info
+    - echo "cargo build --verbose --all-features --workspace"
+    # - cargo test --verbose --all-features --no-fail-fast --workspace
+    # # coverage with branches
+    # - grcov . --source-dir . --output-type lcov --llvm --branch --ignore-not-existing
+    #     --ignore "/*" --ignore "tests/*" --output-path lcov-w-branch.info
+    # - rust-covfix lcov-w-branch.info --output lcov-w-branch-fixed.info
+    # # We'd like to not use a remote bash script for uploading the coverage reports,
+    # # however this job seems to be more tricky than we hoped.
+    # - bash <(curl -s https://codecov.io/bash) -t "$CODECOV_P_TOKEN" -f lcov-w-branch-fixed.info
+    # # lines coverage
+    # - grcov . --source-dir . --output-type lcov --llvm --ignore-not-existing
+    #     --ignore "/*" --ignore "tests/*" --output-path lcov-lines.info
+    # - rust-covfix lcov-lines.info --output lcov-lines-fixed.info
+    # - bash <(curl -s https://codecov.io/bash) -f lcov-lines-fixed.info
 
 clippy-std:
   stage:                           workspace
@@ -187,9 +187,9 @@ clippy-std:
     - job:                         check-std
       artifacts:                   false
   script:
-    - for crate in ${ALL_CRATES}; do
+    - echo "for crate in ${ALL_CRATES}; do
         cargo clippy --verbose --all-features --manifest-path crates/${crate}/Cargo.toml -- -D warnings;
-      done
+      done"
 
 clippy-wasm:
   stage:                           workspace
@@ -198,18 +198,18 @@ clippy-wasm:
     - job:                         check-wasm
       artifacts:                   false
   script:
-    - for crate in ${ALSO_WASM_CRATES}; do
+    - echo "for crate in ${ALSO_WASM_CRATES}; do
         cargo clippy --verbose --no-default-features --manifest-path crates/${crate}/Cargo.toml --target wasm32-unknown-unknown -- -D warnings;
-      done
+      done"
 
 fmt:
   stage:                           workspace
   <<:                              *docker-env
   script:
-    - cargo fmt --verbose --all -- --check
+    - echo "cargo fmt --verbose --all -- --check"
 
     # For the UI tests we need to disable the license check
-    - cargo fmt --verbose --all -- --check --config=license_template_path="" crates/lang/macro/tests/ui/{pass,fail}/*.rs
+    # - cargo fmt --verbose --all -- --check --config=license_template_path="" crates/lang/macro/tests/ui/{pass,fail}/*.rs
 
 
 #### stage:                        examples
@@ -221,17 +221,17 @@ examples-test:
     - job:                         clippy-std
       artifacts:                   false
   script:
-    - for example in examples/*/; do
+    - echo "for example in examples/*/; do
         cargo test --verbose --manifest-path ${example}/Cargo.toml;
-      done
+      done"
 
 examples-fmt:
   stage:                           examples
   <<:                              *docker-env
   script:
-    - for example in examples/*/; do
+    - echo "for example in examples/*/; do
         cargo fmt --verbose --manifest-path ${example}/Cargo.toml -- --check;
-      done
+      done"
 
 examples-clippy-std:
   stage:                           examples
@@ -240,28 +240,28 @@ examples-clippy-std:
     - job:                         clippy-std
       artifacts:                   false
   script:
-    - for example in examples/*/; do
+    - echo "for example in examples/*/; do
         cargo clippy --verbose --manifest-path ${example}/Cargo.toml -- -D warnings;
-      done
+      done"
 
 examples-clippy-wasm:
   stage:                           examples
   <<:                              *docker-env
   script:
-    - for example in examples/*/; do
+    - echo "for example in examples/*/; do
         cargo clippy --verbose --manifest-path ${example}/Cargo.toml --no-default-features --target wasm32-unknown-unknown -- -D warnings;
-      done
+      done"
 
 examples-contract-build:
   stage:                           examples
   <<:                              *docker-env
   script:
     - cargo contract -V
-    - for example in examples/*/; do
+    - echo "for example in examples/*/; do
         pushd $example &&
         cargo contract build &&
         popd;
-      done
+      done"
 
 examples-docs:
     stage:                           examples
@@ -273,9 +273,9 @@ examples-docs:
         # puts the contract functions in a private module.
         # Once https://github.com/paritytech/ink/issues/336 has been implemented we can get rid
         # of this flag.
-        - for example in examples/*/; do
+        - echo "for example in examples/*/; do
             cargo doc --manifest-path ${example}/Cargo.toml --document-private-items --verbose --no-deps;
-          done
+          done"
 
 #### stage:                        publish
 
@@ -298,29 +298,29 @@ publish-docs:
     - unset CARGO_TARGET_DIR
     # Set git config
     - rm .git/config
-    - git config user.email "devops-team@parity.io"
-    - git config user.name "${GITHUB_USER}"
-    - git config remote.origin.url "https://${GITHUB_TOKEN}@github.com/paritytech/ink.git"
-    - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
-    - git fetch origin gh-pages
-    # saving README and docs
-    - cp -r ./crate-docs/ /tmp/doc/
-    - cp README.md /tmp/doc/
-    - cp -r .images/ /tmp/doc/
-    - git checkout gh-pages
-    - mv _config.yml /tmp/doc/
-    # remove everything and restore generated docs, README and Jekyll config
-    - rm -rf ./*
-    - rm -rf ./.images
-    - mv /tmp/doc/* .
-    - mv /tmp/doc/.images .
-    # Upload files
-    - git add --all --force
-    - git status
-    - git commit -m "Updated docs for ${CI_COMMIT_REF_NAME} and pushed to gh-pages"
-    - git push origin gh-pages --force
-  after_script:
-    - rm -rf .git/ ./*
+    - echo "git config user.email "devops-team@parity.io""
+  #   - git config user.name "${GITHUB_USER}"
+  #   - git config remote.origin.url "https://${GITHUB_TOKEN}@github.com/paritytech/ink.git"
+  #   - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
+  #   - git fetch origin gh-pages
+  #   # saving README and docs
+  #   - cp -r ./crate-docs/ /tmp/doc/
+  #   - cp README.md /tmp/doc/
+  #   - cp -r .images/ /tmp/doc/
+  #   - git checkout gh-pages
+  #   - mv _config.yml /tmp/doc/
+  #   # remove everything and restore generated docs, README and Jekyll config
+  #   - rm -rf ./*
+  #   - rm -rf ./.images
+  #   - mv /tmp/doc/* .
+  #   - mv /tmp/doc/.images .
+  #   # Upload files
+  #   - git add --all --force
+  #   - git status
+  #   - git commit -m "Updated docs for ${CI_COMMIT_REF_NAME} and pushed to gh-pages"
+  #   - git push origin gh-pages --force
+  # after_script:
+  #   - rm -rf .git/ ./*
 
 #### stage:                        fuzz
 
@@ -336,25 +336,25 @@ fuzz-tests:
     script:
         # We fuzz-test only crates which possess the `ink-fuzz-tests` feature
         - all_tests_passed=0
-        - for crate in ${ALL_CRATES}; do
+        - echo "for crate in ${ALL_CRATES}; do
             if grep "ink-fuzz-tests =" crates/${crate}/Cargo.toml;
             then
                 cargo test --verbose --features ink-fuzz-tests --manifest-path crates/${crate}/Cargo.toml --no-fail-fast -- fuzz_ || exit_code=$?;
                 all_tests_passed=$(( all_tests_passed | exit_code ));
             fi
-          done
-        - if [ $all_tests_passed -eq 0 ]; then exit 0; fi
-        - |
-             curl -X "POST" "https://api.github.com/repos/paritytech/ink/issues" \
-                -H "Cookie: logged_in=no" \
-                -H "Authorization: token ${GITHUB_TOKEN}" \
-                -H "Content-Type: application/json; charset=utf-8" \
-                -d $'{
-                    "title": "[ci] Failing fuzz tests on master ('"$( date +"%d %b %Y" )"')",
-                    "body": "The CI job ['"${CI_JOB_ID}"']('"${CI_JOB_URL}"') just failed.\n\nThe offending commit is ['"${CI_COMMIT_TITLE}"'](https://github.com/paritytech/ink/commit/'"${CI_COMMIT_SHA}"').",
-                    "assignees": [],
-                    "labels": [
-                        "P-high"
-                    ]
-                }'
-        - exit ${all_tests_passed}
+          done"
+        # - if [ $all_tests_passed -eq 0 ]; then exit 0; fi
+        # - |
+        #      curl -X "POST" "https://api.github.com/repos/paritytech/ink/issues" \
+        #         -H "Cookie: logged_in=no" \
+        #         -H "Authorization: token ${GITHUB_TOKEN}" \
+        #         -H "Content-Type: application/json; charset=utf-8" \
+        #         -d $'{
+        #             "title": "[ci] Failing fuzz tests on master ('"$( date +"%d %b %Y" )"')",
+        #             "body": "The CI job ['"${CI_JOB_ID}"']('"${CI_JOB_URL}"') just failed.\n\nThe offending commit is ['"${CI_COMMIT_TITLE}"'](https://github.com/paritytech/ink/commit/'"${CI_COMMIT_SHA}"').",
+        #             "assignees": [],
+        #             "labels": [
+        #                 "P-high"
+        #             ]
+        #         }'
+        # - exit ${all_tests_passed}
