Fix CI (#2486)
* ci: Run tests on stable

* ci: Enable `RUSTC_BOOTSTRAP` for RISCV builds

* ci: bless selector-overlap test output

* ci: build contracts on stable

* ci: style

* ci: remove unnecessary --all arg from test command

* fix: respect `CARGO_TARGET_DIR` when fetching metadata in e2e contract builds

* ci: re-partition and disable cache for integration tests

* ci: separate job for flaky wildcard selector test

* ci: separate job for flaky debugging strategies test

* ci: ignore static buffer assertion padding pending ink_allocator updates

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -73,7 +73,7 @@ jobs:
             bash --version
             ink-node --version; cargo contract --version; git --version
             echo -e '[registry]\nprotocol = \"sparse\"' > /usr/local/cargo/config.toml
-            echo \"cargo-contract-version=$(cargo +nightly contract --version)\" >> $GITHUB_OUTPUT
+            echo \"cargo-contract-version=$(cargo contract --version)\" >> $GITHUB_OUTPUT
 
   spellcheck:
     runs-on: ubuntu-latest
@@ -328,11 +328,13 @@ jobs:
       - name: Build for RISC-V
         uses: ./.github/run-container-command
         if: ${{ matrix.type == 'RISCV' }}
+        env:
+          RUSTC_BOOTSTRAP: 1
         with:
           command: |
             for crate in ${ALSO_RISCV_CRATES}; do
               echo ${crate};
-              RUSTFLAGS=\"--cfg substrate_runtime\" cargo +nightly build \
+              RUSTFLAGS=\"--cfg substrate_runtime\" cargo build \
                 --no-default-features --release \
                 --target ${CLIPPY_TARGET} \
                 --manifest-path ./crates/${crate}/Cargo.toml \
@@ -367,7 +369,7 @@ jobs:
           QUICKCHECK_TESTS: 0
         with:
           command: |
-            cargo +nightly nextest run --all-features --no-fail-fast --workspace --locked
+            cargo nextest run --all-features --no-fail-fast --workspace --locked
 
   test-docs:
     runs-on: ubuntu-latest
@@ -386,7 +388,7 @@ jobs:
           uses: ./.github/init
           with:
             cache: true
-            cache-directories: ${{ github.workspace}}/${{ env.CARGO_TARGET_DIR }}
+            cache-directories: ${{ github.workspace }}/${{ env.CARGO_TARGET_DIR }}
             cache-key: ${{ matrix.type }}
 
         - name: Test
@@ -403,7 +405,7 @@ jobs:
               QUICKCHECK_TESTS:            0
           with:
             command: |
-                cargo +nightly test --all-features --no-fail-fast --workspace --doc --locked
+                cargo test --all-features --no-fail-fast --workspace --doc --locked
 
   test-linting:
     runs-on: ubuntu-latest
@@ -422,7 +424,7 @@ jobs:
           uses: ./.github/init
           with:
             cache: true
-            cache-directories: ${{ github.workspace}}/${{ env.CARGO_TARGET_DIR }}
+            cache-directories: ${{ github.workspace }}/${{ env.CARGO_TARGET_DIR }}
             cache-key: ${{ matrix.type }}
 
         - name: Test Linting
@@ -453,7 +455,7 @@ jobs:
         uses: ./.github/init
         with:
           cache: true
-          cache-directories: ${{ github.workspace}}/${{ env.CARGO_TARGET_DIR }}
+          cache-directories: ${{ github.workspace }}/${{ env.CARGO_TARGET_DIR }}
 
       - name: Create docs
         uses: ./.github/run-container-command
@@ -463,7 +465,7 @@ jobs:
           command: |
             for package in $(cargo metadata --format-version 1 | jq -r '.workspace_members[]' | awk '{print $1}'); do
               # Run cargo doc for each workspace member
-              cargo +nightly doc --no-deps --all-features -p ${package}
+              cargo doc --no-deps --all-features -p ${package}
             done
             mv ${CARGO_TARGET_DIR}/doc ./crate-docs
             # FIXME: remove me after CI image gets nonroot
@@ -523,6 +525,10 @@ jobs:
   examples-test:
     runs-on: ubuntu-latest
     needs: [fmt]
+    strategy:
+      fail-fast: false
+      matrix:
+        partition: [1, 2, 3, 4]
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -532,9 +538,13 @@ jobs:
       - name: Initialize runner
         uses: ./.github/init
         with:
-          cache: true
-          cache-directories: ${{ github.workspace}}/${{ env.CARGO_TARGET_DIR }}
-          cache-on-failure: true
+          # TODO: (@davidsemakula) Re-enable cache if we can improve its ROI,
+          # currently it eats up more than 65% of disk space, causing this job to run out of disk space,
+          # or require a very large number of partitions, and generally makes this job too flaky.
+          cache: false
+          # cache-directories: ${{ github.workspace }}/${{ env.CARGO_TARGET_DIR }}
+          # cache-on-failure: true
+          # cache-key: ${{ matrix.partition }}
 
       - name: Test Examples
         uses: ./.github/run-container-command
@@ -544,8 +554,9 @@ jobs:
         with:
           # Run all tests with --all-features, which will run the `e2e-tests` feature if present.
           command: |
-            scripts/for_all_contracts_exec.sh --path integration-tests --ignore internal/static-buffer --ignore internal/mapping -- \
-            cargo +nightly test --all-features --all --manifest-path {}
+            scripts/for_all_contracts_exec.sh --path integration-tests --ignore internal/static-buffer --ignore internal/mapping \
+            --ignore public/debugging-strategies --ignore public/wildcard-selector --partition ${{ matrix.partition }}/4 -- \
+            cargo test --all-features --manifest-path {}
 
   examples-test-mapping:
     runs-on: ubuntu-latest
@@ -560,7 +571,7 @@ jobs:
           uses: ./.github/init
           with:
             cache: true
-            cache-directories: ${{ github.workspace}}/${{ env.CARGO_TARGET_DIR }}
+            cache-directories: ${{ github.workspace }}/${{ env.CARGO_TARGET_DIR }}
             cache-on-failure: true
 
         - name: Test Mapping Example
@@ -572,7 +583,54 @@ jobs:
               INK_STATIC_BUFFER_SIZE: 256
           with:
             command: |
-                cargo +nightly test --all --all-features --manifest-path integration-tests/internal/mapping/Cargo.toml
+                cargo test --all-features --manifest-path integration-tests/internal/mapping/Cargo.toml
+
+  # TODO: (@davidsemakula) Add back to `examples-test` job when flakiness is fixed.
+  examples-test-debugging-strategies:
+    runs-on: ubuntu-latest
+    needs: ci-image
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 1
+
+      - name: Initialize runner
+        uses: ./.github/init
+        with:
+          cache: true
+          cache-directories: ${{ github.workspace }}/${{ env.CARGO_TARGET_DIR }}
+          cache-on-failure: true
+
+      - name: Test Wildcard Selector Example
+        uses: ./.github/run-container-command
+        with:
+          command: |
+            cargo test --all-features --manifest-path integration-tests/public/debugging-strategies/Cargo.toml
+
+
+  # TODO: (@davidsemakula) Add back to `examples-test` job when flakiness is fixed.
+  examples-test-wildcard-selector:
+    runs-on: ubuntu-latest
+    needs: ci-image
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 1
+
+      - name: Initialize runner
+        uses: ./.github/init
+        with:
+          cache: true
+          cache-directories: ${{ github.workspace }}/${{ env.CARGO_TARGET_DIR }}
+          cache-on-failure: true
+
+      - name: Test Wildcard Selector Example
+        uses: ./.github/run-container-command
+        with:
+          command: |
+            cargo test --all-features --manifest-path integration-tests/public/wildcard-selector/Cargo.toml
 
   examples-custom-test:
     runs-on: ubuntu-latest
@@ -587,7 +645,7 @@ jobs:
         uses: ./.github/init
         with:
           cache: true
-          cache-directories: ${{ github.workspace}}/${{ env.CARGO_TARGET_DIR }}
+          cache-directories: ${{ github.workspace }}/${{ env.CARGO_TARGET_DIR }}
           cache-on-failure: true
 
       - name: Run E2E test with on-chain contract
@@ -601,12 +659,12 @@ jobs:
           command: |
             # run flipper E2E test with on-chain contract
             ink-node -lruntime::revive=debug 2>&1 &
-            cargo +nightly contract build --release --manifest-path integration-tests/public/flipper/Cargo.toml
-            export CONTRACT_ADDR_HEX=$(cargo +nightly contract instantiate \
+            cargo contract build --release --manifest-path integration-tests/public/flipper/Cargo.toml
+            export CONTRACT_ADDR_HEX=$(cargo contract instantiate \
               --manifest-path integration-tests/public/flipper/Cargo.toml \
               --suri //Alice --args true -x -y --output-json | \
               jq -r .contract | xargs subkey inspect | grep -o "0x.*" | head -n1)
-            CONTRACTS_NODE_URL=ws://127.0.0.1:9944 cargo +nightly test \
+            CONTRACTS_NODE_URL=ws://127.0.0.1:9944 cargo test \
               --features e2e-tests \
               --manifest-path integration-tests/public/flipper/Cargo.toml \
               e2e_test_deployed_contract \
@@ -624,7 +682,7 @@ jobs:
             # the readme + test comments explain why `32`, in short because the tests write
             # content into the buffer and want to provoke an exhaustion of the buffer.
             cargo clean --manifest-path integration-tests/internal/static-buffer/Cargo.toml
-            INK_STATIC_BUFFER_SIZE=32 cargo +nightly test --manifest-path integration-tests/internal/static-buffer/Cargo.toml --all-features
+            INK_STATIC_BUFFER_SIZE=32 cargo test --manifest-path integration-tests/internal/static-buffer/Cargo.toml --all-features
 
   examples-contract-build-riscv:
     runs-on: ubuntu-latest
@@ -639,7 +697,7 @@ jobs:
         uses: ./.github/init
         with:
           cache: true
-          cache-directories: ${{ github.workspace}}/${{ env.CARGO_TARGET_DIR }}
+          cache-directories: ${{ github.workspace }}/${{ env.CARGO_TARGET_DIR }}
           cache-on-failure: true
 
       - name: Extract branch name
@@ -710,7 +768,7 @@ jobs:
         uses: ./.github/init
         with:
           cache: true
-          cache-directories: ${{ github.workspace}}/${{ env.CARGO_TARGET_DIR }}
+          cache-directories: ${{ github.workspace }}/${{ env.CARGO_TARGET_DIR }}
 
       - name: Create Examples Docs
         uses: ./.github/run-container-command
@@ -751,7 +809,7 @@ jobs:
         uses: ./.github/init
         with:
           cache: true
-          cache-directories: ${{ github.workspace}}/${{ env.CARGO_TARGET_DIR }}
+          cache-directories: ${{ github.workspace }}/${{ env.CARGO_TARGET_DIR }}
 
       - name: Fuzz
         uses: ./.github/run-container-command
@@ -766,7 +824,7 @@ jobs:
             for crate in ${ALL_CRATES}; do
               if grep "ink-fuzz-tests =" ./crates/${crate}/Cargo.toml;
               then
-                cargo +nightly test --features ink-fuzz-tests --manifest-path ./crates/${crate}/Cargo.toml --no-fail-fast -- fuzz_ || exit_code=$?;
+                cargo test --features ink-fuzz-tests --manifest-path ./crates/${crate}/Cargo.toml --no-fail-fast -- fuzz_ || exit_code=$?;
                 all_tests_passed=$(( all_tests_passed | exit_code ));
               fi
             done
